@ProductManagerApi_HostAddress = https://localhost:7067/api/v1
@ProductManagerApi_ProductPrefix= {{ProductManagerApi_HostAddress}}/product
@ProductManagerApi_BasicAuth=Basic YWRtaW46YWRtaW4=

### must return 200
GET {{ProductManagerApi_HostAddress}}/public/
Accept: application/json

### must return 401
GET {{ProductManagerApi_HostAddress}}/protected/
Accept: application/json

### must return 200 with Authorization header
GET {{ProductManagerApi_HostAddress}}/protected/
Authorization: {{ProductManagerApi_BasicAuth}}
Accept: application/json

### Get all products from the database
GET {{ProductManagerApi_ProductPrefix}}/
Accept: application/json

### if the product with id 1 exists, must return 200 otherwise 404
GET {{ProductManagerApi_ProductPrefix}}/1
Accept: application/json

###

### Create a new product
POST {{ProductManagerApi_ProductPrefix}}/create
Content-Type: application/json
Authorization: {{ProductManagerApi_BasicAuth}}

{
  "name": "Product 11",
  "price": 100
}

### Must return 400 Name field is required
POST {{ProductManagerApi_ProductPrefix}}/create
Content-Type: application/json
Authorization: {{ProductManagerApi_BasicAuth}}

{
  "price": 100,
  "available": true
}

### return 200
PUT {{ProductManagerApi_ProductPrefix}}/update
Content-Type: application/json
Authorization: {{ProductManagerApi_BasicAuth}}

{
  "id": 1,
  "name": "Product 102",
  "price": 100
}
### 
DELETE {{ProductManagerApi_ProductPrefix}}/delete/1
Authorization: {{ProductManagerApi_BasicAuth}}




